### ISSUE TITLE
Cairo regions don't have an API

### ISSUE THREAD

**Issue by pontaoski** [jwharm/java-gi#107]
They're non-GObject types, but some of the GObject types require them for certain methods. There's no way to create them at the moment.

**Comment by jwharm** [comment]
There are three static `create` methods for Regions: https://jwharm.github.io/cairo-java-bindings/javadoc/org.freedesktop.cairo/org/freedesktop/cairo/Region.html#create(org.freedesktop.cairo.RectangleInt)

**Comment by jwharm** [comment]
@pontaoski OK to close this?
