### ISSUE TITLE
Repeated segfault: "Loading hsdis library failed"

### ISSUE THREAD

**Issue by ToxicStoxm** [jwharm/java-gi#116]
So basically every time I run my app (java-gi  0.10.2), it crashes because of a segfault after 1-10 minutes. I almost feel like it's random and because of that I can't locate the problematic code. I attached two files which contain log:

*The applications log with 'G_MESSAGES_DEBUG=all ' environment variable, this also includes my custom log (It's mostly irrelevant)*
[LCCP.log](https://github.com/user-attachments/files/16315339/LCCP.log)

*'coredumpctl info' output*
[LCCP-coredump.log](https://github.com/user-attachments/files/16315340/LCCP-coredump.log)

_If any additional information is required don't hesitate to ask. (The problem could also very well just me being an idiot, just so you know)_

**Comment by jwharm** [comment]
I can't find anything in the log files that would explain the segfaults.
I browsed through LCCP source code and noticed that you call Gtk functions from threads ([example](https://github.com/ToxicStoxm/LED-Suite/blob/main/src/main/java/com/toxicstoxm/lccp/ui/Window.java#L435)). That could be the cause of the segfaults. Can you wrap these calls in a `MainContext::invoke` or `GLib::idleAddOnce` and see if this solves the issue?

Btw, the "Loading hsdis library failed" message is unrelated. It means you don't have the hotspot disassembler plugin installed, but that's normal.

**Comment by ToxicStoxm** [comment]
Thanks for the response! I will look into it today.

**Comment by ToxicStoxm** [comment]
I used GLib::idleAddOnce and after two hours of not crashing I'm almost certain that this fixxed the segfaults! Thanks for your help.
