### ISSUE TITLE
Add Scala examples

### ISSUE THREAD

**Issue by jwharm** [jwharm/java-gi#135]
Add Scala examples to the java-gi-examples repository.

**Comment by poach3r** [comment]
Hello, is this still needed? If so, where?

**Comment by jwharm** [comment]
Hi, yes this would still be very much appreciated.

There are a few small example applications for java-gi in the [jwharm/java-gi-examples](https://github.com/jwharm/java-gi-examples) repository. They are all written in Java, except for the spacewar game, that one is Kotlin. I'd love to include one or more examples in Scala, so Scala developers can use it to get started with Java-GI.

The example could be a port of an existing one (like the notepad app) but it can also be something new.
The app should be small enough to be easily understandable, but it would also be really nice if it showcases a few unique Scala features.

**Comment by jwharm** [comment]
The sources for the website are in the java-gi repository itself, under the [docs](https://github.com/jwharm/java-gi/tree/main/docs) folder.

**Comment by poach3r** [comment]
Would you also like some more Kotlin examples? I can likely finish those before the Scala ones since I much more familiar with it.

**Comment by jwharm** [comment]
Yes certainly!

**Comment by jwharm** [comment]
Resolved with https://github.com/jwharm/java-gi-examples/pull/2
