### ISSUE TITLE
 Separate Interop Package for Java-GI to Remove GLib Dependency

### ISSUE THREAD

**Issue by webfolderio** [jwharm/java-gi#167]
Java-GI is nice cli tool, and the generated code is much better than other tools like jextract. However, the generated bindings depend on `io.github.jwharm.javagi.interop`, which requires glib in the classpath.

It would be great if the interop package could be separated from glib and published as a standalone library. This would make Java-GI usable for C libraries that don’t rely on GLib or GTK.

**Comment by jwharm** [comment]
Thank you for trying out Java-GI, and for the suggestion!

I don't think it will work out well:
- The Java-GI core functionality heavily uses concepts defined by GObject and GLib, such as `GType`.
- Most (if not all) libraries that support language bindings through GObject-Introspection, use the core modules (GLib and GObject) anyway, so the dependency on glib will usually be there.
