### ISSUE TITLE
Enums that were previously handled as bitfields can no longer be extended

### ISSUE THREAD

**Issue by BwackNinja** [jwharm/java-gi#172]
This commit changed how Flags are handled, which is cleaner but too restrictive: https://github.com/jwharm/java-gi/commit/ac888ae5ee9ab6923458e65554afa2937d47671d

Unfortunately, that breaks using `org.freedesktop.gstreamer.gst.Buffer.map` when using the flag `GstGL.MAP_GL = 131072`, defined in GstGL-1.0.gir. Without that, you cannot read GL frames from gstreamer when using java-gi, which is needed when using a shared context between gtk and gstreamer to display hardware GL video frames.

**Comment by jwharm** [comment]
Apparently `MapFlags` used by `Buffer.map()` is an "open enum" and GstGL adds their own flag constant.

I'll change this specific enum into `int` constants so that it will work.
