### ISSUE TITLE
Switch for Enumerations

### ISSUE THREAD

**Issue by JFronny** [jwharm/java-gi#19]
Currently, the Enumeration model makes the usage of switch statements (for example in Dialog.onResponse) impossible.
One possible fix for this would be to convert it to a class with `public static final` fields containing normal ints and auxiliary methods.
A MagicConstant annotation could be used on method parameters to improve the developer experience.

**Comment by jwharm** [comment]
`@MagicConstant` is Intellij specific. Users of other IDEs would only see an int. (I'd like to see if I can get Gnome Builder 43 to work with a Java language server.)

I used `enum`s for enumerations earlier. I had to generate conversion functions to get the constant value. [Here's an example.](https://github.com/jwharm/java-gi-generated-sources/blob/a73e0054aee1c4621abb34e1aa274b9068e264da/src/org/cairographics/Antialias.java) This became confusing when working with arrays of enumerations, so I changed it to the current design. But in theory, it should work.
