### ISSUE TITLE
 org.gnome.adw.ExpanderRow.titleLines returns Boolean instead of Int

### ISSUE THREAD

**Issue by gavr123456789** [jwharm/java-gi#96]
![image](https://github.com/jwharm/java-gi/assets/30507409/2b9c5220-8090-40c5-80dc-086fd14770a1)

Return Type must be int 
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.ExpanderRow.title-lines.html

**Comment by jwharm** [comment]
This is actually a gboolean:
[https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.ExpanderRow.get_title_lines.html](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.ExpanderRow.get_title_lines.html)

So it seems to be a bug in LibAdwaita.
You can work around it using `lines = (int) expanderRow.getProperty("title-lines")`.

**Comment by badcel** [comment]
Seems to be fixed in [current Gir-Files](https://github.com/gircore/gir-files/blob/558027f28bd6d84e829eb173bfee7e992a3762c6/linux/Adw-1.gir#L15760) already.

**Comment by jwharm** [comment]
I logged https://gitlab.gnome.org/GNOME/libadwaita/-/issues/844 upstream
